---
title: "Using OLS Regression to Predict Median House Values in Philadelphia"
subtitle: "Statistical and Data Mining Methods - MUSA 500"
author:
  - name: "Changhao Li"
    affiliation: "Student"
  - name: "Eugene Brusilovskiy"
    affiliation: "Professor"
date: "2022-10-18"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

```{css, echo=FALSE}
pre {
  max-height: 300px;
  overflow-y: auto;
}

pre[class] {
  max-height: 300px;
}
```

```{r setup, include=FALSE,echo=FALSE}
library(knitr)
opts_chunk$set(collapse = TRUE, prompt = TRUE, echo = TRUE)
library(tidyverse)
library(DAAG)
library(MASS)
library(ggpmisc)
library(stargazer) 
rm(list=ls()) 

options(scipen = 999)

```

```{r, loadData}
regData <- read.csv("E:/course/2022/Musa500/Homework_Assignments_export/HW 1/RegressionData.csv")
```

```{r, summaryStatistics}
summary(regData)
sd(regData$MEDHVAL)
sd(regData$PCTBACHMOR)
sd(regData$NBELPOV100)
sd(regData$PCTVACANT)
sd(regData$PCTSINGLES)

```

```{r, visPreTransformation, fig.width=12, fig.height=8}
par(mfrow=c(3,2))
hist(regData$MEDHVAL)
hist(regData$PCTBACHMOR)
hist(regData$NBELPOV100)
hist(regData$PCTVACANT)
hist(regData$PCTSINGLES)

```

```{r, fig.width=12, fig.height=8}
par(mfrow=c(3,2))
tregData <-
	regData %>%
	mutate(LNMEDHVAL = log(MEDHVAL),
				 LNPCTBACHMOR = log(1+PCTBACHMOR),
				 LNNBELPOV100 = log(1+NBELPOV100),
				 LNPCTVACANT = log(1+PCTVACANT),
				 LNPCTSINGLES = log(1+PCTSINGLES),
				 LNMEDHHINC = log(MEDHHINC)
				 )
```

```{r, fig.width=12, fig.height=18}

par(mfrow=c(5,2))
hist(tregData$MEDHVAL,breaks = 20)
hist(tregData$LNMEDHVAL,breaks = 20)
hist(tregData$PCTBACHMOR, breaks = 20)
hist(tregData$LNPCTBACHMOR, breaks = 20)
hist(tregData$NBELPOV100, breaks = 20)
hist(tregData$LNNBELPOV100, breaks = 20)
hist(tregData$PCTVACANT, breaks = 20)
hist(tregData$LNPCTVACANT, breaks = 20)
hist(tregData$PCTSINGLES, breaks = 20)
hist(tregData$LNPCTSINGLES, breaks = 20)

```

```{r, dfForRegression}
dtregdata <- tregData %>%
	dplyr::select(-MEDHVAL, -NBELPOV100, -LNPCTBACHMOR, -LNPCTVACANT, -LNPCTSINGLES)

```

```{r, fig.width=9, fig.height=9}

par(mfrow=c(2,2))
plot(dtregdata$LNNBELPOV100, dtregdata$LNMEDHVAL)
plot(dtregdata$PCTBACHMOR, dtregdata$LNMEDHVAL)
plot(dtregdata$PCTVACANT, dtregdata$LNMEDHVAL)
plot(dtregdata$PCTSINGLES, dtregdata$LNMEDHVAL)

```

```{r, correlations}
regressionVars <- dtregdata %>% 
			dplyr::select(-POLY_ID, -AREAKEY, -LNMEDHHINC, -MEDHHINC)

matrix <- cor(regressionVars)
matrix

```

```{r}
library(ggcorrplot)
ggcorrplot(cor(regressionVars),outline.col = "white",lab =T)
```

```{r, results='hide', fig.show='hide'}
predLM <- lm(LNMEDHVAL ~ PCTBACHMOR+PCTVACANT+PCTSINGLES+LNNBELPOV100, data = regressionVars)
summary(predLM)

anova(predLM)

predLM$predFit <- fitted(predLM)
predLM$predResids <- residuals(predLM)
predLM$predRStand <- rstandard(predLM)

# Check for standardized residuals
plot(predLM$predFit, predLM$predRStand)

reg_result <- data.frame(predFit = predLM$predFit, predR_stand = predLM$predRStand)
g_reg = ggplot(reg_result, aes(x = predFit, y = predR_stand)) +
  geom_point(color="grey", size=1) +
  geom_smooth(method="lm", color="black") +
  labs(x="Predict Values", y="Standardized Residual") +
  stat_poly_eq(aes(label = paste(after_stat(eq.label),
                                 after_stat(rr.label), sep = "*\", \"*"))) 
g_reg
```

```{r standard residuals}
hist(predLM$predRStand,breaks = 80)
```

```{r}
library(car)

predLM <- lm(LNMEDHVAL ~ PCTBACHMOR+PCTVACANT+PCTSINGLES+LNNBELPOV100, data = regressionVars)

vif(predLM)
```

HERE LIES THE STEPWISE REGRESSION

```{r, stepwise}
step <- stepAIC(predLM, direction="both")

step$anova
```

```{r, results='hide', fig.show='hide'}
kFold1 <- CVlm(data = dtregdata, predLM, 5)

# Extract Mean Standard Errors & RMSE:
mse <- attr(kFold1, "ms")
rmse <- sqrt(mse)
```

```{r, results='hide', fig.show='hide'}
regVars2 <- 
	dtregdata %>%
	dplyr::select(LNMEDHVAL, PCTVACANT, MEDHHINC)

predLM2 <- lm(LNMEDHVAL ~ PCTVACANT+MEDHHINC, data = regVars2)
summary(predLM2)

regVars2$predFit2 <- fitted(predLM2)
regVars2$predResids2 <- residuals(predLM2)
regVars2$predRStand2 <- rstandard(predLM2)

# Attempt to link residuals to main dataset
residsDF <- 
	regVars2 %>%
	mutate(residuals = residuals(predLM2))

# Check for standardized residuals
plot(regVars2$predFit2, regVars2$predRStand2)
```

```{r, results='hide', fig.show='hide'}
kFold2 <- CVlm(data = regVars2, predLM2, 5)

# Extract Mean Standard Errors & RMSE:
mse2 <- attr(kFold2, "ms")
rmse2 <- sqrt(mse2)
```

```{r}
regResids <- regData %>%
  mutate(residuals = residuals(predLM), 
         residuals2 = residuals(predLM2)) %>%
  group_by(POLY_ID, residuals, residuals2) 

  
regResids = regResids[c("POLY_ID", "residuals", "residuals2")]
```
